name       : neko
version    : 2.3.0
release    : 15
source     :
    - https://github.com/HaxeFoundation/neko/archive/refs/tags/v2-3-0.tar.gz : 850e7e317bdaf24ed652efeff89c1cb21380ca19f20e68a296c84f6bad4ee995
homepage   : https://nekovm.org/
license    :
    - Apache-2.0
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
    - Zlib
component  : programming
summary    : Neko is a high-level dynamically typed programming language
description: |
    Neko is a high-level dynamically typed programming language. It can be used as an embedded scripting language. It has been designed to provide a common runtime for several different languages.
builddeps  :
    - pkgconfig(apr-util-1)
    - pkgconfig(bdw-gc)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
    - git
    - httpd-devel
    - mbedtls-devel
setup      : |
    %patch -p1 < $pkgfiles/neko-discard-xlocale.patch
    %patch -p1 < $pkgfiles/neko-gtk3.patch
    %cmake_ninja -DRUN_LDCONFIG=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
