name       : neko
version    : 2.3.0
release    : 9
source     :
    - https://github.com/HaxeFoundation/neko/archive/v2-3-0.tar.gz : 850e7e317bdaf24ed652efeff89c1cb21380ca19f20e68a296c84f6bad4ee995
license    :
    - Apache-2.0
    - BSD-2-Clause
    - GPL-2.0
    - MIT
    - Zlib
component  : programming
summary    : Neko is a high-level dynamically typed programming language.
description: |
    Neko is a high-level dynamically typed programming language.
builddeps  :
    - pkgconfig(apr-util-1)
    - pkgconfig(bdw-gc)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpcre)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
    - git
    - httpd-devel
    - mbedtls-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
